<?php


namespace ViralsPackage\ViralsInventory\Tests;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use ViralsPackage\ViralsInventory\ViralsInventoryServiceProvider;
use Faker\Factory as Faker;

class TestCase extends \Orchestra\Testbench\TestCase
{
    use DatabaseTransactions;
    protected $faker;

    protected function getPackageProviders($app)
    {
        return [
            ViralsInventoryServiceProvider::class
        ];
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Faker::create();
    }
}