<?php


namespace ViralsPackage\ViralsInventory\Tests;

use ViralsPackage\ViralsInventory\app\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use ViralsPackage\ViralsInventory\ViralsInventoryServiceProvider;
use Faker\Factory as Faker;
use Carbon\Carbon;

class TestCase extends \Orchestra\Testbench\TestCase
{
    use DatabaseTransactions;
    protected $faker;

    protected function getPackageProviders($app)
    {
        return [
            ViralsInventoryServiceProvider::class
        ];
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Faker::create();
    }

    public function setupFakeDatabase()
    {
        $user = User::create([
            [
                'name'  => 'hungtd',
                'email' => 'hungtd@viralsoft.vn',
                'password' => bcrypt('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now()
            ]
        ]);
        
        return $user;
    }
}
